Disable RemoteSettingsCrashPull
The crash reporter component (we disable with the --disable-crashreporter
option in mozconfig) ships the RemoteSettingsCrashPull.sys.mjs module.
Without it we occasionally get

    Error: Failed to load resource://gre/modules/RemoteSettingsCrashPull.sys.mjs

on browser start with uBlock Origin and some other extensions enabled, which
causes Web pages to stop loading.

Fixes #134.

Signed-off-by: celenity <celenity@celenity.dev>